service: authorization-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-south-1

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin

custom:
  webpack:
    webpackConfig: './webpack.config.cjs'

functions:
  basicAuthorizer:
    handler: src/handlers/basic-authorizer.basicAuthorizer
    
