service: import-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-south-1
  stage: dev
  iamRoleStatements:
    - Effect: Allow
      Action: s3:ListBucket
      Resource: arn:aws:s3:::aws-training-product-import-bucket
    - Effect: Allow
      Action:
        - s3:*
      Resource: arn:aws:s3:::aws-training-product-import-bucket/*
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: arn:aws:sqs:ap-south-1:915264841307:create-product-queue

plugins:
  - serverless-webpack
  - serverless-auto-swagger

custom:
  webpack:
    webpackConfig: './webpack.config.cjs'

functions:
  importProductsFile:
    handler: src/handlers/import-products-file.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true

  importFileParser:
    handler: src/handlers/import-file-parser.importFileParser
    events:
      - s3:
          bucket: aws-training-product-import-bucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
